### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mikebutts** [dsmillie/dvp-u6-who-data#1]
Criteria 1: DataFrames and CSV
_Score Level:_4
_Comment(s): Great job at using the CSV data!
Criteria 2: Implementation of visualizations
_Score Level: 4
_Comment(s): Great job at implementing the visualizations!
Criteria 3: Responses and Blog post
_Score Level: 4
_Comment(s): Great Job with being able to make a solid post with a good explanation of the data for context!
Overall Score: 12/12
Great job with this project. It appears to me that you are doing an excellent job of being able to take data and make visualizations using Python. Pat yourself on the back for getting this far! You are doing great things! If you feel comfortable with it try applying what you learned here to other open data sets!

**Comment by dsmillie** [comment]
Thanks very much!
